# Generated by Django 3.2.25 on 2025-01-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mark_as_paid',
            field=models.BooleanField(default=False),
        ),
    ]
